# This file was generated by GoReleaser. DO NOT EDIT.
cask "janitor" do
  name "janitor"
  desc "Janitor – tidy your folders by file type (CLI organizer)."
  homepage "https://github.com/BioHazard786/Janitor"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "janitor"

  on_macos do
    on_intel do
      url "https://github.com/BioHazard786/Janitor/releases/download/v#{version}/Janitor_Darwin_x86_64.tar.gz"
      sha256 "234b3801da02806a29a71057f01cfa2d50141be7a5a51ef2e9a494ac8d2bbdeb"
    end
    on_arm do
      url "https://github.com/BioHazard786/Janitor/releases/download/v#{version}/Janitor_Darwin_arm64.tar.gz"
      sha256 "883e4a8d5d0d29e91b19e120d6a4977a755554adbec5d7f53fbaaa8de72374f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BioHazard786/Janitor/releases/download/v#{version}/Janitor_Linux_x86_64.tar.gz"
      sha256 "72347849379828a07310b72c184296ea3a1dc1637ef8246264bdde9d4b74cef8"
    end
    on_arm do
      url "https://github.com/BioHazard786/Janitor/releases/download/v#{version}/Janitor_Linux_arm64.tar.gz"
      sha256 "a671ad781edf48b9ebb398472871a3ada2a9f10cae90e770d11ea70a05458d99"
    end
  end

  # No zap stanza required
end
