# This file was generated by GoReleaser. DO NOT EDIT.
cask "warpdrop" do
  name "warpdrop"
  desc "A simple, secure p2p file sharing tool using WebRTC technology."
  homepage "https://github.com/BioHazard786/Warpdrop"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warpdrop"

  on_macos do
    on_intel do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_macOS-64bit.tar.gz"
      sha256 "8d894fe0d66733588f61c9dbe6b15d51cec7db45184bf6abf874017c9941c96d"
    end
    on_arm do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_macOS-ARM64.tar.gz"
      sha256 "22469b213a3215a2c7ab71e19dc992ea15a4d2609c9461602da17e163056bc5b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_Linux-64bit.tar.gz"
      sha256 "a96ffcf0cd958f1db7b574437e95077fed692b16f1b4e442b3becce3f7e17750"
    end
    on_arm do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_Linux-ARM64.tar.gz"
      sha256 "b654f60c3af46498a85f3ae535a5f31aae841ae5ce19bf56a69e0da8ac932cdb"
    end
  end

  # No zap stanza required
end
