# This file was generated by GoReleaser. DO NOT EDIT.
cask "warpdrop" do
  name "warpdrop"
  desc "A simple, secure p2p file sharing tool using WebRTC technology."
  homepage "https://github.com/BioHazard786/Warpdrop"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warpdrop"

  on_macos do
    on_intel do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_macOS-64bit.tar.gz"
      sha256 "3779a1776d413adc409c0dba00e08dcda15ee31b496e260c1dd0a53221290a72"
    end
    on_arm do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_macOS-ARM64.tar.gz"
      sha256 "006f25add2d17d91059d85b8c0d550e8f2bf0e51e7b952c7ba6fd2dbdbd229c9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_Linux-64bit.tar.gz"
      sha256 "1add1e168f66d514668c1b9b4735c25867f8946b473f3b8cfa7d16b6c49fce2f"
    end
    on_arm do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_Linux-ARM64.tar.gz"
      sha256 "27ff3d2d6f8011130a8cdc72cdf0dc77dab623a397c22fbe822bf3b17f5d2d5a"
    end
  end

  # No zap stanza required
end
