# This file was generated by GoReleaser. DO NOT EDIT.
cask "warpdrop" do
  name "warpdrop"
  desc "A simple, secure p2p file sharing tool using WebRTC technology."
  homepage "https://github.com/BioHazard786/Warpdrop"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warpdrop"

  on_macos do
    on_intel do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_macOS-64bit.tar.gz"
      sha256 "86e9c601fb14e0a483c2ef3425f81623098215131824d3839f1c747cf5ea67bf"
    end
    on_arm do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_macOS-ARM64.tar.gz"
      sha256 "f06e606a1b3fb48f7ceb0175ccdce7e9c7ce2c83a18b65ef98708047724ddaef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_Linux-64bit.tar.gz"
      sha256 "c6a2f5d4ad3f9193fadbe78cff9881270d93f76ddb3e85ffbd47631d3268d9bb"
    end
    on_arm do
      url "https://github.com/BioHazard786/warpdrop/releases/download/v#{version}/warpdrop_v#{version}_Linux-ARM64.tar.gz"
      sha256 "57c81071d286c0bb33cc38623fe2b601ac0cc7929993959853c652dbb685e447"
    end
  end

  # No zap stanza required
end
